### PR TITLE
 Cleanup the format, constants, and unused function

### LINKED ISSUE #236: Clean up the format, constants, and unused functions
run go fmt on whole project
move some hard code string to constants
remove unused functions
rename import package to meet the Go coding convention, such as ds_models

### LINKED ISSUE #239: Consistently apply import alias go-mod-core-contract models
go-mod-core-contract is commonly imported as a package in DS SDK source files.

To reference models originating from this module in a manner consistent with edgex-go services, let's alias the import as "contract".

### PR DESCRIPTION
**Pull request by cloudxxx8**
run go fmt on whole project
move some hard code string to constants
remove unused functions
rename import package to meet the Go coding convention, such as
ds_models and contract
fix #236
fix #239
Remove unused comment and to do items

### CODE REVIEW

**Comment by tobiasmo1** [comment]
Instead of dsModel should this be "dsModels" since it references the SDK "models" package?

**Comment by cloudxxx8** [comment]
@tobiasmo1 I used dsModels.  I changed because we are using "contract", not "contracts"
Do you think we should use "contract" and "dsModels"?  If yes, I will modify them.

**Comment by tobiasmo1** [comment]
Yes, I recommend dsModels and contract.

Think of contract as shorthand for contractModels.

**Comment by cloudxxx8** [comment]
@tobiasmo1 I've updated the PR.  Please help review again.

**Pull request merged**
