### PR TITLE
fix: issue-1397

### PR DESCRIPTION
**Pull request by gq-tang**
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
Thanks for the fix

DCO is failed
Please sign off your commit, and modify the commit message to the better subject
https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines#CommittingCodeGuidelines-CommitMessages

**Comment by cloudxxx8** [comment]
@FelixTing please help verify this fix when you have time

**Comment by lenny-intel** [comment]
@gq-tang , please use descriptive commit message/ PR tile, rather than referencing the issue number. We use the commit messages to auto generate the Change Log. So these messages are in fact release notes.

**Comment by lenny-intel** [comment]
@gq-tang , please don't not skip completing the PR check list. This is required.

**Pull request closed without merging**
