### PR TITLE
chore: Non-breaking version bumps of edgex dependencies

### PR DESCRIPTION
**Pull request by bnevis-i**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?) Unit test only.
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
"make test"

### CODE REVIEW

**Comment by bnevis-i** [comment]
@lindseysimple Feel free to merge on my behalf.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by lindseysimple** [comment]
@bnevis-i It seems that this PR is no longer needed as the version bumps has been included in latest main.

**Comment by bnevis-i** [comment]
Thx. Closing.

**Pull request closed without merging**
