### PR TITLE
feat: Enable Registry and Config access token

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-c/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?
Registry/Config access token not supported

## What is the new behavior?
Registry/Config access token now supported

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jim-wang-intel — DISMISSED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
Please update the attribution.txt

[2021-03-29T23:57:58.595Z] ./bin/test-attribution-txt.sh
[2021-03-29T23:57:58.595Z] An attribution for golang.org/x/crypto is missing from in  Attribution.txt, please add

**Review by iain-anderson — CHANGES_REQUESTED** [review]
Filename is configured twice?

**Comment by lenny-intel** [comment]
> Filename is configured twice?

@iain-anderson Yes, because it is used for both the Registry and the Configuration Provider. Too maintain that separation, we must configure it for each.

**Comment by lenny-intel** [comment]
> Please update the attribution.txt
> 
> [2021-03-29T23:57:58.595Z] ./bin/test-attribution-txt.sh
> [2021-03-29T23:57:58.595Z] An attribution for golang.org/x/crypto is missing from in Attribution.txt, please add

@cloudxxx8 , fixed.

**Review by cloudxxx8 — APPROVED** [review]
LGTM
please resolve the conflict.  thanks.

**Review by jim-wang-intel — APPROVED** [review]
LGTM

**Review by iain-anderson — APPROVED** [review]
LGTM

**Pull request merged**
