### PR TITLE
refactor: Replace file based with use of Secret Provider to get Access Tokens

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-c/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?
Currently expecting the Registry/Config Access tokens to be retrieved for files using the file location config settings.

## What is the new behavior?
Now uses SecretProvider to retrieve the access tokens.
File location config settings have been removed

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

BREAKING CHANGE: All App Services running with the secure Edgex Stack now need to have the SecretStore configured, a Vault token created and run with EDGEX_SECURITY_SECRET_STORE=true.

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jim-wang-intel — DISMISSED** [review]
LGTM

**Review by bnevis-i — APPROVED** [review]

**Review by iain-anderson — COMMENTED** [review]
Should `(Config)AccessTokenFile` be removed from the example configuration?

**Comment by lenny-intel** [comment]
> Should `(Config)AccessTokenFile` be removed from the example configuration?

@iain-anderson yes, thought I had. Done now. THX!

**Review by bnevis-i — APPROVED** [review]

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
