### PR TITLE
Add release notes for Fuji

### PR DESCRIPTION
**Pull request by cloudxxx8**
Add a release notes to state the changes and known issues in Fuji
release.

Fix https://github.com/edgexfoundry/device-sdk-go/issues/393

Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
@iain-anderson once we fix #345, `NewCommandValue` func can be used as expected in device-rest-go.
However, I am not sure why you mention https://github.com/edgexfoundry/device-sdk-c/pull/206 here?

**Comment by iain-anderson** [comment]
Sorry, links now fixed

**Comment by cloudxxx8** [comment]
@iain-anderson it's clear now.  After merging #346, `NewCommandValue()` for binary data will be the same as `NewBinaryValue()`.  Device Service can use `NewCommandValue()`, and it won't cause any error in the future.  `NewCommandValue()` is just encoding CBOR twice right now.
I modified the release note as follows:
o ISSUE#345:  NewCommandValue function makes an unnecessary CBOR encoding.

Please see it's fine to merge or we need more modification.  Thanks.

**Comment by iain-anderson** [comment]
OK. We'll need to move the VERSION on the master branch again

**Comment by cloudxxx8** [comment]
> OK. We'll need to move the VERSION on the master branch again

What do we exactly need to do?

**Pull request merged**
