### PR TITLE
feat!: Apply JWT authentication to incoming calls

### PR DESCRIPTION
**Pull request by bnevis-i**
BREAKING CHANGE: Incoming REST API calls must have a JWT authentication token, with the exception
of /api/v2/ping.

This change is related to the implementation of the microservice authentication (token-based) ADR.
This commit also consumes the breaking interface change to go-mod-core-contracts.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
As a library, there is no way to directly test the effect of this change, other than "make test",
until it is integrated into downstream device clients.

### CODE REVIEW

**Comment by bnevis-i** [comment]
@iain-anderson Please help assign a reviewer.

**Review by hahattan — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
@hahattan or @iain-anderson,  I don't have committer rights in this repo.  Could one of you merge for me?

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
