### PR TITLE
Remove RO 'property=value' from example devprof

### PR DESCRIPTION
**Pull request by tonyespy**
The original EdgeX device profile required an attribute ('property')
in a device profile ResourceOperation that was always set to 'value'.
As such, this attribute was removed from the model, but still exists
in the example device profile YAML.

Fixes issue #247

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@weichou1229 @FelixTing 
Please make the same change on MQTT, Modbus, Random, and Virtual accordingly.
Thanks.

**Comment by tonyespy** [comment]
> Looks good. I do see some straggler references though; i.e., search for `property":`
> 
> Could we clean this out of the static entries to this 'property' field in values used to populate mock_deviceclient and mock_deviceprofileclient?

This PR was just about cleaning up the example profile. If there are other references to "property" in the SDK, please open a separate issue.

**Comment by tonyespy** [comment]
> @weichou1229 @FelixTing
> Please make the same change on MQTT, Modbus, Random, and Virtual accordingly.
> Thanks.

@cloudxxx8 Can you please open issues for these repositories instead?

**Comment by cloudxxx8** [comment]
yes, they will open the issues

**Comment by cloudxxx8** [comment]
@tobiasmo1 could you please approve this PR, and I will open another PR to modify the mock clients?

**Comment by cloudxxx8** [comment]
please see #264

**Pull request merged**
