### PR TITLE
Update Makefile and clean attribution file

### LINKED ISSUE #472: Run Data Race Detector in makefile for unit test
According to the recent WG meeting, we should verify the service with Data Race Detector
Refer to: 
https://github.com/edgexfoundry/edgex-go/blob/28c25972b4512281f3666373bb21b36fa0252d7e/Makefile#L71
https://golang.org/doc/articles/race_detector.html

### PR DESCRIPTION
**Pull request by hahattan**
update makefile to be consistent with edgex-go (add data race detector
for unit test) and remove unused attributions in Attribution.txt

Signed-off-by: Chris Hung <chris@iotechsys.com>

fix #472

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines#CommittingCodeGuidelines-CommitMessages
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### CODE REVIEW

**Comment by cloudxxx8** [comment]
recheck

**Comment by hahattan** [comment]
It seems edgexBuildGoApp pipeline didn't set the `GOTESTFLAGS` like the latest parallel pipeline did:
https://github.com/edgexfoundry/edgex-global-pipelines/blob/69b11ffe9275ab8e68c4cba724b6d595bdc2db9b/vars/edgeXBuildGoParallel.groovy#L99

@ernestojeda do you think we should update the GoApp pipeline or we wait until go1.15 to add the data race detector ?

**Comment by ernestojeda** [comment]
@hahattan Correct. We only implemented the GOTESTFLAGS on edgex-go. My preference would be to wait until Go 1.15 to enable the race condition testing across the rest of the repos.

**Comment by cloudxxx8** [comment]
upgraded to Go 1.15, so remove the hold label

**Comment by hahattan** [comment]
verified that the `-race` flag is correctly applied in jenkins pipeline.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
