### PR TITLE
fix: Create a buffer to handle the AsyncValues

### PR DESCRIPTION
**Pull request by weichou1229**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines#CommittingCodeGuidelines-CommitMessages
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
The asyncBufferSize not work as expected, all the async value wait in the same queue.

Issue Number: #552 

## What is the new behavior?
To enhance performance, refactor function to create a buffer and use goroutine for sending each AsyncValues.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by iain-anderson** [comment]
Note that this issue is planned to be discussed at the Architects' meeting 20th August and the PR should not be merged prior to that

**Comment by iain-anderson** [comment]
Re: the above comment, this was discussed in the Device WG 3rd August and it is agreed that operation in parallel is permitted. Documentation should note that events may arrive out-of-order in core-data / app service, and should show how to configure so as to enforce same-order (ie, single threaded processing)

**Comment by weichou1229** [comment]
@iain-anderson Added the comment on the processAsyncResults function.

**Comment by tonyespy** [comment]
@weichou1229 can you re-base this PR, so I can review? I'm out next week, so would like to get this done before my absence.

**Comment by weichou1229** [comment]
@tonyespy No problem, rebased the branch.

**Review by tonyespy — COMMENTED** [review]
Please update this branch from master (note, 'git pull -r' can be used to do this without creating a "merge master into issue-552" commit).

My only other comment is whether this should be considered a "fix" PR vs. a "re-factor" PR as it is resolving an issue. To me, "refactor" means reworking the code solely for the purpose of simplifying the code and/or preparing for a future change. This PR actually changes the functionality to resolve a bug report / issue.

**Comment by weichou1229** [comment]
@tonyespy 
You are right!  Rebased the branch and modified the commit message.

**Review by tonyespy — APPROVED** [review]
LGTM

**Pull request merged**
