### PR TITLE
Create Attribution.txt

### LINKED ISSUE #132: Create Attribution.txt

### PR DESCRIPTION
**Pull request by cloudxxx8**
fix #132

Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>

### CODE REVIEW

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by cloudxxx8** [comment]
According to the comment from @anonymouse64 
I updated the Attribution.txt again

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
the build issue will be fixed after merging #136

**Pull request merged**
