### PR TITLE
GET/PUT cmd should return 423 when the operatingState of device set to DISABLED

### LINKED ISSUE #390: GET/PUT command still succeed when the operatingState of device set to DISABLED
OS version: ubuntu 18.04
EdgeX version: Master branch (Fuji)
Environment details: Docker container

Steps to reproduce:
1. Start device-virtual service.
2. Create a device profile.
3. Create a device that used the above device profile and the operatingState set to DISABLED, request body as below.
```
{
   "origin":1471806386919,
   "name" :"Disabled-Device",
   "description":"operatingState parameter of device set to disabled",
   "adminState":"UNLOCKED",
   "operatingState":"DISABLED",
   "protocols":{
      "other":{
         "Address"  : "simple01",
          "Port" : "300"
      }
   },
   "labels":[
      "device-example"
   ],
   "location":"{lat:45.45,long:47.80}",
   "responseDelay":0,
   "service":{
      "name":"device-virtual"
   },
   "profile":{
      "name":"Sample-Profile"
   }
}
```
4. Sending get command for the device.
API :  /api/v1/device/{device_id}/{command_name}
Method: GET

Expected result: Get return code 423
Actual result: Get return code 200

### PR DESCRIPTION
**Pull request by weichou1229**
GET/PUT command should return code 423 when the operatingState of device set to DISABLED
Fix #390

### CODE REVIEW

**Comment by weichou1229** [comment]
recheck

**Comment by cloudxxx8** [comment]
@weichou1229 please rebase this PR

**Comment by weichou1229** [comment]
Done.

**Comment by cloudxxx8** [comment]
@weichou1229 please also pick this commit to fuji branch

**Pull request merged**
