### PR TITLE
refactor: Remove obsolete code from Add Secret

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-c/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?
Add secret has obsolete code to ensure path has correct slashes.

## What is the new behavior?
Obsolete code removed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]
the unit test should also be modified

**Comment by lenny-intel** [comment]
> the unit test should also be modified

@cloudxxx8 Done

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
recheck

**Pull request merged**
