### PR TITLE
removed the code to disable Device OperatingState when creating Device Cache

### PR DESCRIPTION
**Pull request by cloudxxx8**
removed the code to disable Device OperatingState when creating Device Cache

Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@jduranf are you able to merge this PR?  Thanks

**Comment by jduranf** [comment]
sorry @cloudxxx8, I can't approve or merge in device-sdk-go

**Comment by cloudxxx8** [comment]
thanks, I got it, @jduranf 
@SteveOss could you please help merge this PR? Joan has helped reviewed it.

**Comment by cloudxxx8** [comment]
@tonyespy  re-committed with the message you requested.  please help merge the code.  Thanks

**Pull request merged**
