### PR TITLE
feat(security): Enable gosec and default linter set

### LINKED ISSUE #1029: Add "make lint" target and add to "make test" target
Should enable golangci-lint with default linters + gosec.

See https://github.com/edgexfoundry/edgex-go/issues/3565

### PR DESCRIPTION
**Pull request by bnevis-i**
Fixes #1029

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) N/A
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?) Yes
- [ ] I have opened a PR for the related docs change (if not, why?)
N/A

## Testing Instructions
```make test```

NOTE: There are two remaining issues that need advising.

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
I need help resolving the following two failures:

These weren't as straightforward as the other linter warnings.

```
[2022-01-05T05:50:07.760Z] internal/messaging/messaging.go:84:5: S1000: should use a simple channel send/receive instead of `select` with a single case (gosimple)
[2022-01-05T05:50:07.761Z] 				select {
[2022-01-05T05:50:07.761Z] 				^
[2022-01-05T05:50:07.761Z] internal/autodiscovery/autodiscovery.go:48:4: SA2000: should call wg.Add(1) before starting the goroutine to avoid a race (staticcheck)
[2022-01-05T05:50:07.761Z] 			wg.Add(1)
```

**Comment by hahattan** [comment]
> I need help resolving the following two failures:
> 
> These weren't as straightforward as the other linter warnings.
> 
> ```
> [2022-01-05T05:50:07.760Z] internal/messaging/messaging.go:84:5: S1000: should use a simple channel send/receive instead of `select` with a single case (gosimple)
> [2022-01-05T05:50:07.761Z] 				select {
> [2022-01-05T05:50:07.761Z] 				^
> [2022-01-05T05:50:07.761Z] internal/autodiscovery/autodiscovery.go:48:4: SA2000: should call wg.Add(1) before starting the goroutine to avoid a race (staticcheck)
> [2022-01-05T05:50:07.761Z] 			wg.Add(1)
> ```

First one it suggests remove the select-case statement:
```Go
go func() {
	defer wg.Done()
	<-ctx.Done()
	if msgClient != nil {
		_ = msgClient.Disconnect()
	}
	lc.Infof("Disconnected from MessageBus")
}()
```

For the second one move the `wg.Add(1)` call before spawning go routine:
```Go
if runDiscovery {
    wg.Add(1)
    go func() {
        defer wg.Done()
        ...
    }()
}
```

**Comment by bnevis-i** [comment]
@hahattan 

Thanks, Chris.  I will get these suggestions merged and update the PR later this morning.

**Comment by bnevis-i** [comment]
@hahattan

Pushed.  Ready for re-review.

**Review by hahattan — APPROVED** [review]
LGTM

**Comment by bnevis-i** [comment]
Not a committer on this repo.  Need someone else to merge.

**Pull request merged**
