### PR TITLE
Remove RO 'property=value' from mock clients

### LINKED ISSUE #263: Remove RO 'property=value' from mock clients
This issue is related to #247, and the property=value should also be removed from mock clients

### PR DESCRIPTION
**Pull request by cloudxxx8**
The original EdgeX device profile required an attribute ('property')
in a device profile ResourceOperation that was always set to 'value'.
As such, this attribute was removed from the model, but still exists
in the mock clients.
fix #263

Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
recheck

**Comment by tobiasmo1** [comment]
@cloudxxx8 referenced PR#248 to be merged first. It needs rebase.

**Comment by cloudxxx8** [comment]
rebased
the nested addressable will be removed from another PR

**Comment by cloudxxx8** [comment]
@tobiasmo1 , I just rebased this PR to resolve the unit test issue.
basically, I don't make any further change.  please review again.  thanks

**Comment by cloudxxx8** [comment]
recheck

**Pull request merged**
