### PR TITLE
Make Put command accept simple JSON map

### LINKED ISSUE #141: Make Put command body accept simple JSON type
Currently, put command accept JSON array only, like
`[{"key1":"value1"}, {"key2":"value2"}]`
It could be improved to also accept
`{"key1":"value1", "key2":"value2"}`

### PR DESCRIPTION
**Pull request by cloudxxx8**
fix #141
Also made a minor fix for Attribution.txt

Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>

### CODE REVIEW

**Comment by tonyespy** [comment]
@SteveOss After sleeping on it, I agree with you about 0.7.2, as much as I don't like it. As this PR is proposed against master, it should be revised to just handle the map of parameters. I'll update the device services requirements document, and will publish a new version to the wiki before the holiday break.

**Comment by cloudxxx8** [comment]
@tonyespy I will update the PR and make it support map only in master, map and array both in delhi, and separate different change with different PR, such as Attribution.txt, version number, and configuration

**Comment by cloudxxx8** [comment]
@tonyespy 
I've made the change and it accept map format for Put command parameters only.
Also, I removed the change for Attribution.txt, but keep the change of configuration.toml, or device-simple will be broken by this change.
Please help review again.  Thanks.

**Comment by cloudxxx8** [comment]
@tonyespy , the conflict has been resolved.  Please help review again.  Thanks

**Comment by cloudxxx8** [comment]
@tonyespy the commit is rebased, please help take a look

**Pull request merged**
