### PR TITLE
Added /device/name/{name}/{command} API

### PR DESCRIPTION
**Pull request by jduranf**
Signed-off-by: Joan Duran <jduran@circutor.com>

### CODE REVIEW

**Comment by jduranf** [comment]
Fix #84

**Comment by cloudxxx8** [comment]
this issue didn't impact the basic feature and we don't have time to test it thoroughly.
I suggest hold and merge this PR after Delhi

**Comment by tonyespy** [comment]
Based on Cloud's comment above, let's hold off and ensure that this is well-tested. We can release as part of 0.7.1 which will also contain the new system management endpoints.

**Comment by cloudxxx8** [comment]
Since delhi branch has been tagged, merge this PR to master, and we will start some test based on master.

**Pull request merged**
