### PR TITLE
feat: Device ProtocolProperties have typed values

### PR DESCRIPTION
**Pull request by hahattan**
related to edgexfoundry/go-mod-core-contracts#592

consume ProtocolProperties type changes in go-mod-core-contracts. AutoDiscovery handler will still parse property as string type and compare with ProvisionWatcher regex identifier.

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

1. Run `device-simple` from this branch with `DEVICE_DISCOVERY_ENABLED: true` 
2. Verify autodiscovery is working correctly by seeing logs like:
```shell
level=INFO ts=2023-03-08T03:37:44.264246Z app=device-simple source=async.go:105 msg="Adding discovered device Simple-Device02 to Metadata"
level=DEBUG ts=2023-03-08T03:37:44.268304Z app=device-simple source=validation.go:58 msg="Device validation request received on message queue. Topic: edgex/device-simple/validate/device, Correlation-id: 9d070e7b-cf91-41a7-96eb-e489340aa754"
level=DEBUG ts=2023-03-08T03:37:44.269186Z app=device-simple source=validation.go:100 msg="Device validation response published on message queue. Topic: edgex/response/device-simple/8d3145ec-aa52-4d3b-8b43-e86e833a996e, Correlation-id: 9d070e7b-cf91-41a7-96eb-e489340aa754"
level=DEBUG ts=2023-03-08T03:37:44.270504Z app=device-simple source=async.go:173 msg="Discovered Device Simple-Device03 Port value cannot be 399"
level=DEBUG ts=2023-03-08T03:37:44.270522Z app=device-simple source=async.go:128 msg="Filtered device addition finished"
```

### CODE REVIEW

**Review by cloudxxx8 — DISMISSED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@hahattan, @cloudxxx8 , This is breaking change. Please make sure future breaking changes are flag appropriately. Yes, I should have not approved until commit was updated appropriately.

**Comment by cloudxxx8** [comment]
apologize again

**Pull request merged**
